"use client";
import { useState, useEffect } from "react";
import { submitForApproval, getApprovalHistory } from "../../lib/api";
import { useAuth } from "../../lib/auth-context";
type ApprovalRecord = { id: string; status: string; requested_by_name: string; decided_by_name: string | null; comment: string | null; created_at: string; decided_at: string | null; };
export default function ApprovalPanel({ entityType, entityId, entityStatus, onStatusChange }: { entityType: "CHANGE" | "CAPA" | "INCIDENT" | "NC"; entityId: string; entityStatus: string; onStatusChange?: () => void; }) {
  const { user } = useAuth();
  const [history, setHistory] = useState<ApprovalRecord[]>([]);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const canSubmit = user?.role !== "VIEWER" && !["PENDING_APPROVAL","CLOSED","APPROVED","CANCELLED"].includes(entityStatus);
  useEffect(() => { (async () => { try { setHistory(await getApprovalHistory(entityType, entityId)); } catch {} })(); }, [entityType, entityId, success]);
  const handleSubmit = async () => { setSubmitting(true); setError(""); setSuccess(""); try { await submitForApproval(entityType, entityId); setSuccess("Submitted for approval."); onStatusChange?.(); } catch (e: any) { setError(e.message || "Failed"); } finally { setSubmitting(false); } };
  return (<div style={{ background: "#fff", borderRadius: 10, border: "1px solid #e5e7eb", padding: 16, marginTop: 16 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }}><div style={{ fontSize: 13, fontWeight: 700, color: "#111" }}>Approval</div>{canSubmit && <button onClick={handleSubmit} disabled={submitting} style={{ padding: "5px 14px", fontSize: 12, fontWeight: 600, borderRadius: 6, cursor: "pointer", background: "#111", color: "#fff", border: "none" }}>{submitting ? "Submitting..." : "Submit for Approval"}</button>}{entityStatus === "PENDING_APPROVAL" && <span style={{ fontSize: 11, fontWeight: 700, color: "#92400e", background: "#fffbeb", padding: "3px 10px", borderRadius: 10 }}>Awaiting Approval</span>}</div>{error && <div style={{ fontSize: 12, color: "#dc2626", marginBottom: 8 }}>{error}</div>}{success && <div style={{ fontSize: 12, color: "#16a34a", marginBottom: 8 }}>{success}</div>}{history.length > 0 && <div style={{ borderTop: "1px solid #f3f4f6", paddingTop: 10 }}>{history.map(h => (<div key={h.id} style={{ display: "flex", alignItems: "flex-start", gap: 10, padding: "6px 0", fontSize: 12 }}><span style={{ flexShrink: 0, fontSize: 10, fontWeight: 700, padding: "2px 8px", borderRadius: 8, background: h.status === "APPROVED" ? "#f0fdf4" : h.status === "REJECTED" ? "#fef2f2" : "#fffbeb", color: h.status === "APPROVED" ? "#16a34a" : h.status === "REJECTED" ? "#dc2626" : "#92400e" }}>{h.status}</span><div style={{ flex: 1 }}><span style={{ color: "#374151" }}>{h.status === "PENDING" ? `Requested by ${h.requested_by_name}` : `${h.status === "APPROVED" ? "Approved" : "Rejected"} by ${h.decided_by_name}`}</span>{h.comment && <div style={{ color: "#6b7280", fontStyle: "italic", marginTop: 2 }}>{h.comment}</div>}<div style={{ color: "#9ca3af", fontSize: 11, marginTop: 1 }}>{new Date(h.decided_at || h.created_at).toLocaleString()}</div></div></div>))}</div>}{history.length === 0 && !canSubmit && entityStatus !== "PENDING_APPROVAL" && <div style={{ fontSize: 12, color: "#9ca3af" }}>No approval history</div>}</div>);
}
